"""Autonomous Development Engine core package."""

from .acceptance import AcceptanceReport, CheckResult, build_report
from .autonomous_planner import (
    AutonomousPlanningResult,
    PlannerDisposition,
    PlannerPolicy,
    PlannerProposal,
    PlannerTaskProposal,
    PlannerValidationError,
    PlanningProvider,
    ValidatedPlannerProposal,
    accept_validated_proposal,
    build_planner_prompt,
    plan_high_level_goal,
    validate_planner_proposal,
)
from .activity import ActivityEvent, ActivityKind
from .campaign import (
    AutonomousCampaign,
    CampaignEvidenceSummary,
    CampaignStatus,
    summarize_campaign_evidence,
)
from .campaign_runtime import complete_campaign_task, derive_campaign_status
from .campaign_store import CampaignStore, DEFAULT_CAMPAIGN_PATH
from .activity_store import ActivityStore
from .checkpoint import CheckpointState, TaskCheckpoint
from .checkpoint_runtime import CheckpointedCycleExecution, run_checkpointed_cycle
from .checkpoint_store import CheckpointStore
from .checkpoint_transition import (
    checkpoint_for_completed,
    checkpoint_for_repair_plan,
    checkpoint_for_session,
    checkpoint_from_completed,
    checkpoint_from_repair_plan,
    checkpoint_from_session,
)
from .cycle import (
    CycleFailed,
    CyclePaused,
    CycleResult,
    CycleSession,
    CycleTask,
    CycleTimedOut,
    HumanInputRequired,
    monitor_cycle_session,
    run_cycle,
    start_cycle_session,
)
from .decision_store import DecisionStore
from .decisions import (
    DecisionPriority,
    DecisionRecord,
    DecisionRequest,
    DecisionResponse,
    DecisionStatus,
)
from .health import health_snapshot
from .human_interrupt import HumanInterruptCoordinator
from .improvement_signal import (
    ImprovementEvidenceKind,
    ImprovementEvidenceRef,
    ImprovementSignal,
    ImprovementSignalError,
    ImprovementSignalKind,
    build_improvement_signal,
    build_improvement_signal_id,
)
from .improvement_signal_extraction import (
    ImprovementSignalExtractionError,
    extract_actionable_release_gap_signal,
    extract_verified_release_followup_signal,
)
from .improvement_signal_ledger import (
    ImprovementSignalLedger,
    ImprovementSignalLedgerError,
)
from .improvement_signal_resolution import (
    ImprovementResolutionEntry,
    ImprovementResolutionPolicy,
    ImprovementResolutionReason,
    ImprovementResolutionState,
    ImprovementSignalResolution,
    ImprovementSignalResolutionError,
    resolve_improvement_signals,
    signal_priority,
)
from .jules_planner import (
    JulesPlannerClient,
    JulesPlannerConfig,
    JulesPlannerError,
    JulesPlanningProvider,
    extract_structured_proposal,
    latest_plan_steps,
)
from .interrupt_policy import (
    DecisionKind,
    InterruptDisposition,
    InterruptPolicy,
    decide_interrupt,
)
from .mission_control import (
    MissionActivitySummary,
    MissionCheckpointSummary,
    MissionControlSnapshot,
    MissionDecisionSummary,
    MissionPreviewSummary,
    MissionReleaseSummary,
    MissionTelemetrySummary,
    build_mission_control_snapshot,
)
from .mission_control_html import render_mission_control
from .models import ProjectState, ProjectStatus, TaskStatus
from .planning_activation import (
    PlanningActivationBundle,
    PlanningGoalRequest,
    build_planning_activation,
)
from .pilot import (
    PilotAcceptanceCheck,
    PilotAction,
    PilotContract,
    PilotProviderPolicy,
    PilotSafetyEnvelope,
    PilotTarget,
)
from .pilot_store import PilotContractStore
from .pilot_activation import (
    PilotActivation,
    build_pilot_activation,
    pilot_contract_fingerprint,
    pilot_target_writes_allowed,
    require_pilot_target_write_activation,
)
from .pilot_activation_store import PilotActivationStore
from .pilot_evidence import (
    PilotAcceptanceEvidence,
    PilotFinalEvidence,
    build_pilot_final_evidence,
)
from .pilot_evidence_store import PilotEvidenceStore
from .pilot_dry_run import (
    DryRunCheckStatus,
    PilotDryRunOperation,
    PilotDryRunOperationResult,
    PilotDryRunReport,
    run_pilot_dry_run,
)
from .pilot_preflight import (
    PilotPreflightCheck,
    PilotPreflightReport,
    PreflightCheckKind,
    PreflightCheckStatus,
    run_pilot_preflight,
)
from .preview import PreviewKind, PreviewManifest
from .preview_store import PreviewStore
from .providers.github_copilot import GitHubCopilotProvider
from .provider_availability import (
    ProviderAvailabilityRecord,
    ProviderAvailabilityState,
    evaluate_availability,
    evaluate_provider_availability_state,
)
from .provider_availability_store import ProviderAvailabilityStore
from .provider_registry import ProviderRegistration, ProviderRegistry
from .provider_router import (
    ProviderAvailability,
    ProviderAvailabilitySnapshot,
    RoutingDecision,
    RoutingOutcome,
    RoutingSkip,
    route_provider,
)
from .provider_routing import (
    ProviderCapability,
    ProviderCostClass,
    ProviderDescriptor,
    RoutingRequest,
)
from .routed_execution import RoutedCycleExecution, RoutedExecutionOutcome, run_routed_cycle
from .repair import FailureKind, RepairDisposition, RepairPolicy, RepairState, decide_repair
from .repair_planner import RepairPlan, plan_repair
from .repair_runtime import RepairExecution, map_repair_execution, run_cycle_with_repair
from .release_candidate import (
    ReleaseCandidate,
    ReleaseCandidateError,
    ReleaseEnvironment,
    ReleaseEvidenceKind,
    ReleaseEvidenceRef,
    build_release_candidate,
    build_release_candidate_id,
)
from .release_readiness import (
    ReleaseReadinessDecision,
    ReleaseReadinessError,
    derive_release_readiness,
)
from .release_policy import (
    ReleasePolicyError,
    ReleasePromotionPolicy,
    ReleaseTransitionPlan,
    plan_release_transition,
)
from .release_approval import (
    ReleaseApprovalDecision,
    ReleaseApprovalDisposition,
    ReleaseApprovalError,
    build_release_approval_request,
    evaluate_release_approval,
    request_release_approval,
)
from .release_deployment import (
    ReleaseDeploymentActivation,
    ReleaseDeploymentAdapterRegistration,
    ReleaseDeploymentCompletion,
    ReleaseDeploymentDispatch,
    ReleaseDeploymentError,
    ReleaseDeploymentInvocation,
    ReleaseDeploymentObservation,
    ReleaseDeploymentReceipt,
    ReleaseDeploymentStatus,
    TrustedReleaseDeploymentRegistry,
    arm_release_deployment,
    execute_trusted_release_deployment,
    record_release_deployment_dispatch,
    record_release_deployment_observation,
)
from .release_post_verification import (
    ReleasePostVerificationActivation,
    ReleasePostVerificationBinding,
    ReleasePostVerificationDisposition,
    ReleasePostVerificationError,
    ReleasePostVerificationFinalization,
    ReleasePostVerificationOutcome,
    arm_release_post_verification,
    build_release_post_verification_binding,
    evaluate_release_post_verification,
    finalize_release_post_verification,
)
from .release_observability import (
    ReleaseApprovalViewState,
    ReleaseContainmentViewState,
    ReleaseDeploymentViewState,
    ReleaseObservabilityError,
    ReleaseObservabilitySnapshot,
    ReleasePromotionViewState,
    ReleaseVerificationViewState,
    build_release_observability_snapshot,
)
from .resume import ResumeAction, ResumeDecision, decide_resume
from .task_graph import GraphTaskStatus, TaskGraph, TaskNode
from .task_graph_store import TaskGraphStore
from .task_scheduler import next_runnable_task, runnable_tasks
from .task_graph_transition import resume_task_after_decision, transition_task
from .zero_touch_start import StartDecision, StartDisposition, evaluate_zero_touch_start

__all__ = [
    "AcceptanceReport",
    "ActivityEvent",
    "AutonomousCampaign",
    "AutonomousPlanningResult",
    "CampaignEvidenceSummary",
    "CampaignStatus",
    "CampaignStore",
    "DEFAULT_CAMPAIGN_PATH",
    "ActivityKind",
    "ActivityStore",
    "CheckResult",
    "CheckpointState",
    "CheckpointStore",
    "CheckpointedCycleExecution",
    "CycleFailed",
    "CyclePaused",
    "CycleResult",
    "CycleSession",
    "CycleTask",
    "CycleTimedOut",
    "DecisionKind",
    "InterruptDisposition",
    "InterruptPolicy",
    "DecisionPriority",
    "DecisionRecord",
    "DecisionRequest",
    "DecisionResponse",
    "DecisionStatus",
    "DecisionStore",
    "DryRunCheckStatus",
    "FailureKind",
    "HumanInputRequired",
    "GitHubCopilotProvider",
    "GraphTaskStatus",
    "HumanInterruptCoordinator",
    "ImprovementEvidenceKind",
    "ImprovementEvidenceRef",
    "ImprovementSignal",
    "ImprovementSignalError",
    "ImprovementSignalKind",
    "ImprovementSignalExtractionError",
    "ImprovementSignalLedger",
    "ImprovementSignalLedgerError",
    "ImprovementResolutionEntry",
    "ImprovementResolutionPolicy",
    "ImprovementResolutionReason",
    "ImprovementResolutionState",
    "ImprovementSignalResolution",
    "ImprovementSignalResolutionError",
    "JulesPlannerClient",
    "JulesPlannerConfig",
    "JulesPlannerError",
    "JulesPlanningProvider",
    "MissionActivitySummary",
    "MissionCheckpointSummary",
    "MissionControlSnapshot",
    "MissionDecisionSummary",
    "MissionPreviewSummary",
    "MissionReleaseSummary",
    "MissionTelemetrySummary",
    "PlannerDisposition",
    "PlannerPolicy",
    "PlannerProposal",
    "PlannerTaskProposal",
    "PlannerValidationError",
    "PlanningProvider",
    "ValidatedPlannerProposal",
    "PlanningActivationBundle",
    "PlanningGoalRequest",
    "PilotAcceptanceCheck",
    "PilotAcceptanceEvidence",
    "PilotActivation",
    "PilotActivationStore",
    "PilotAction",
    "PilotContract",
    "PilotContractStore",
    "PilotPreflightCheck",
    "PilotPreflightReport",
    "PreflightCheckKind",
    "PreflightCheckStatus",
    "PilotDryRunOperation",
    "PilotDryRunOperationResult",
    "PilotDryRunReport",
    "PilotEvidenceStore",
    "PilotFinalEvidence",
    "PilotProviderPolicy",
    "PilotSafetyEnvelope",
    "PilotTarget",
    "PreviewKind",
    "PreviewManifest",
    "PreviewStore",
    "ProviderAvailability",
    "ProviderAvailabilityRecord",
    "ProviderAvailabilitySnapshot",
    "ProviderAvailabilityState",
    "ProviderAvailabilityStore",
    "ProviderCapability",
    "ProviderCostClass",
    "ProviderDescriptor",
    "ProviderRegistration",
    "ProviderRegistry",
    "RoutingDecision",
    "RoutingOutcome",
    "RoutingRequest",
    "RoutingSkip",
    "RoutedCycleExecution",
    "RoutedExecutionOutcome",
    "ProjectState",
    "ProjectStatus",
    "RepairDisposition",
    "RepairExecution",
    "RepairPlan",
    "RepairPolicy",
    "RepairState",
    "ReleaseCandidate",
    "ReleaseCandidateError",
    "ReleaseEnvironment",
    "ReleaseEvidenceKind",
    "ReleaseEvidenceRef",
    "ReleaseReadinessDecision",
    "ReleaseReadinessError",
    "ReleasePolicyError",
    "ReleasePromotionPolicy",
    "ReleaseTransitionPlan",
    "ReleaseApprovalDecision",
    "ReleaseApprovalDisposition",
    "ReleaseApprovalError",
    "ReleaseDeploymentActivation",
    "ReleaseDeploymentAdapterRegistration",
    "ReleaseDeploymentCompletion",
    "ReleaseDeploymentDispatch",
    "ReleaseDeploymentError",
    "ReleaseDeploymentInvocation",
    "ReleaseDeploymentObservation",
    "ReleaseDeploymentReceipt",
    "ReleaseDeploymentStatus",
    "TrustedReleaseDeploymentRegistry",
    "ReleasePostVerificationActivation",
    "ReleasePostVerificationBinding",
    "ReleasePostVerificationDisposition",
    "ReleasePostVerificationError",
    "ReleasePostVerificationFinalization",
    "ReleasePostVerificationOutcome",
    "ReleaseApprovalViewState",
    "ReleaseContainmentViewState",
    "ReleaseDeploymentViewState",
    "ReleaseObservabilityError",
    "ReleaseObservabilitySnapshot",
    "ReleasePromotionViewState",
    "ReleaseVerificationViewState",
    "ResumeAction",
    "ResumeDecision",
    "TaskCheckpoint",
    "TaskGraph",
    "TaskGraphStore",
    "TaskNode",
    "TaskStatus",
    "StartDecision",
    "StartDisposition",
    "accept_validated_proposal",
    "build_mission_control_snapshot",
    "build_planning_activation",
    "build_planner_prompt",
    "build_pilot_activation",
    "build_pilot_final_evidence",
    "build_report",
    "build_release_candidate",
    "build_release_candidate_id",
    "derive_release_readiness",
    "plan_release_transition",
    "build_release_approval_request",
    "evaluate_release_approval",
    "request_release_approval",
    "arm_release_deployment",
    "execute_trusted_release_deployment",
    "record_release_deployment_dispatch",
    "record_release_deployment_observation",
    "arm_release_post_verification",
    "build_release_post_verification_binding",
    "evaluate_release_post_verification",
    "finalize_release_post_verification",
    "build_release_observability_snapshot",
    "checkpoint_for_completed",
    "checkpoint_for_repair_plan",
    "checkpoint_for_session",
    "checkpoint_from_completed",
    "checkpoint_from_repair_plan",
    "checkpoint_from_session",
    "complete_campaign_task",
    "decide_interrupt",
    "derive_campaign_status",
    "decide_repair",
    "decide_resume",
    "evaluate_availability",
    "extract_structured_proposal",
    "evaluate_provider_availability_state",
    "evaluate_zero_touch_start",
    "validate_planner_proposal",
    "build_improvement_signal",
    "build_improvement_signal_id",
    "extract_actionable_release_gap_signal",
    "extract_verified_release_followup_signal",
    "resolve_improvement_signals",
    "signal_priority",
    "health_snapshot",
    "latest_plan_steps",
    "map_repair_execution",
    "monitor_cycle_session",
    "next_runnable_task",
    "pilot_contract_fingerprint",
    "pilot_target_writes_allowed",
    "plan_high_level_goal",
    "plan_repair",
    "render_mission_control",
    "require_pilot_target_write_activation",
    "resume_task_after_decision",
    "route_provider",
    "runnable_tasks",
    "run_checkpointed_cycle",
    "run_cycle",
    "run_cycle_with_repair",
    "run_pilot_dry_run",
    "run_pilot_preflight",
    "run_routed_cycle",
    "start_cycle_session",
    "summarize_campaign_evidence",
    "transition_task",
]
